services:
  - type: web
    name: sgpagri
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        scope: build
      - key: NODE_ENV
        value: production
