services:
  - type: web
    name: sgpagri-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: build
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: sgpagri-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://sgpagri-backend.onrender.com/api
